Update local dev setup steps
CodeWithAloha/HIERR pull request #148
Opened 2023-08-15 06:59 UTC by MichaelTamaki

Update local dev setup steps

2023-08-15 07:35 UTC, MichaelTamaki commented on .nvmrc
> +lts/hydrogen
This matches the latest NodeJS version used by the Github Action https://github.com/CodeWithAloha/HIERR/blob/ef477b6b534db8987f14a871e42751615b54ed90/.github/workflows/test-build.yml#L16

Is this file okay to be added? Will it affect the production server?

2023-08-15 07:35 UTC, MichaelTamaki commented on compose.yaml
> +    image: rnwood/smtp4dev:v3
https://github.com/rnwood/smtp4dev

This opens up a SMTP server locally, with a web interface on http://localhost:3001. This way you don't have to set up a SMTP server via Google or whatnot.

2023-08-15 07:35 UTC, MichaelTamaki commented on src/README.md
> +        - docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=<YourStrong@Passw0rd>" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-latest
I was getting an error in bash because of the `!`. Not sure why... But I used the default password from the official docs https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash

2023-08-15 07:35 UTC, MichaelTamaki commented on .env.defaults
This file just makes it easier to set up a `.env` file without having to copy paste line by line from the README. It also provides default values for `DATABASE_URL`, `EMAIL_SERVER`, and `EMAIL_FROM`.

2023-08-15 07:35 UTC, MichaelTamaki commented on compose.yaml
This makes it possible to start up the SQL server via `docker compose up -d` and you don't have to think hard about it 👍

2023-08-15 07:35 UTC, MichaelTamaki commented on src/README.md
> +```bash
These commands were all run in Ubuntu (via Github Codespaces). Not sure what this would look like for Windows.

2023-08-27 21:30 UTC, avenmia requested changes
The PR seems good, but I can't figure out why the build is failing. The error says there's an issue prerendering the polis page, but nothing in your PR seems to affect it. Can you see if the nvmrc is what's causing it? I'd be surprised if it was, but I'm not sure what is causing the issue. Since we have the deployment working on production, I'm hesitant to push anything that could break the production deployment. I'm really excited to start up SQL Server with docker compose!

2023-08-27 21:43 UTC, avenmia requested changes

2023-08-27 21:43 UTC, avenmia commented on .env.defaults
> +NEXT_PUBLIC_POLIS_SURVEYS='[{"id": "{yourSurveyID1}", "title": "{yourSurveyTitle1}", "description", "{yourSurveyDescription1}"}, ...]'
Try changing this so that it's valid JSON, I *think* that's what's breaking the build

2023-08-27 21:44 UTC, tyliec commented on .env.defaults
> +NEXT_PUBLIC_POLIS_SURVEYS='[{"id": "{yourSurveyID1}", "title": "{yourSurveyTitle1}", "description", "{yourSurveyDescription1}"}, ...]'
```suggestion
NEXT_PUBLIC_POLIS_SURVEYS='[{"id": "{yourSurveyID1}", "title": "{yourSurveyTitle1}", "description", "{yourSurveyDescription1}"}]'
```

2023-08-27 21:49 UTC, tyliec commented on .env.defaults
> +NEXT_PUBLIC_POLIS_SURVEYS='[{"id": "{yourSurveyID1}", "title": "{yourSurveyTitle1}", "description", "{yourSurveyDescription1}"}]'
```suggestion
NEXT_PUBLIC_POLIS_SURVEYS='[{"id": "{yourSurveyID1}", "title": "{yourSurveyTitle1}", "description": "{yourSurveyDescription1}"}]'

```

2023-08-27 22:11 UTC, avenmia submitted a review, later dismissed

2023-09-04 22:16 UTC, MichaelTamaki commented
I don't think the issue was `.env.defaults`. Could you check the secrets value that it is initializing the `.env` file with? `secrets.NEXT_PUBLIC_POLIS_SURVEYS`. 

https://github.com/CodeWithAloha/HIERR/blob/main/.github/workflows/test-build.yml#L30

In the meantime, I've updated the Github Actions build step to just copy the `.env.defaults` file to `.env`.

2023-09-24 21:55 UTC, dinoboy197 commented on .nvmrc
> +lts/hydrogen
It's probably best the node version that's used in production, which is major version 18, minor version 14. Anything in the 18 series >= version 14 is probably fine.

2023-10-03 05:56 UTC, avenmia approved these changes
lgtm!

2023-10-04 02:57 UTC, merged