Update src/README with instructions on using sqlite
CodeWithAloha/HIERR pull request #161
Opened 2023-10-10 10:45 UTC by dancyy

2023-10-11 00:36 UTC, MichaelTamaki commented on src/README.md
> +# Prisma SQLite
Can you add a note on why someone would want to use SQLite?

2023-10-13 20:31 UTC, tyliec commented
When submitting PRs, it is helpful to link the issue you are working on (in this case, https://github.com/CodeWithAloha/HIERR/issues/160).

Fun fact: You can also have your issue be automatically closed when your PR gets merged, read more here: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

Thanks for your contribution :)

2023-10-14 02:09 UTC, avenmia requested changes

2023-10-14 02:09 UTC, avenmia commented on src/README.md
> +>Learn more of why someone would want to use this free & open source library here: [When to use SQLite?](https://www.sqlite.org/whentouse.html)
The benefit to using SQLite is that it may be an easier alternative to stand up to SQL Server if someone is trying to run the project locally. A caveat is the demographic questions won't load because those are hard coded in the SQL migrations. Add something like the following below the title:

## Motivation
SQLite is a light-weight alternative to Microsoft SQL Server which may be easier to stand up if you're running the project locally. 

Note: The demographic questions will not populate because they are hard-coded in the SQL migrations.

2023-10-17 05:04 UTC, MichaelTamaki commented on src/README.md
> +SQLite is a light-weight alternative to Microsoft SQL Server which may provide an easier setup solution for those running the project locally.
How do you set up SQLite? I see you added configuration instructions to connect to SQLite, but not on how to actually install SQLite.

2023-11-15 09:00 UTC, avenmia approved these changes
lgtm!

2023-12-22 02:36 UTC, merged