installed vitest
CodeWithAloha/HIERR pull request #210
Opened 2024-06-05 22:21 UTC by kobebuckley

2024-06-18 04:06 UTC, avenmia requested changes

2024-06-18 04:06 UTC, avenmia commented on package.json
> +    "@prisma/client": "4.10.0",
The ^ is removed here, can you add it back in?

2024-06-18 04:06 UTC, avenmia commented on src/components/InfoPopup.tsx
> +            className="absolute right-4 top-4 text-2xl lg:text-4xl"
Can you go through and switch these back to their original style order? If it's a prettier issue we can do another prettier PR. The unit tests should all still pass

2024-06-18 20:58 UTC, kobebuckley commented on src/components/InfoPopup.tsx
> +            className="absolute right-4 top-4 text-2xl lg:text-4xl"
I added  /* prettier-ignore */

above that line so now it won't be affected by prettier.

2024-07-04 20:50 UTC, avenmia approved these changes
lgtm! 👍

2024-07-04 23:08 UTC, merged