Add back buttons to several pages
CodeWithAloha/HIERR pull request #217
Opened 2024-08-20 06:02 UTC by dinoboy197

Add back buttons to several UI pages.

2024-08-25 19:42 UTC, dinoboy197 commented
@avenmia I've rebased this against `main` but I cannot test it fully locally due to #222 . Once #222 is resolved, I'll be able to test all of the pages and make sure that back buttons work correctly.

2024-08-25 20:59 UTC, dinoboy197 commented
@avenmia ready for review :)

2024-08-27 02:33 UTC, avenmia requested changes

2024-08-27 02:33 UTC, avenmia commented on src/components/AddressSearch.tsx
> +              </button>
Let's change this to Home instead of Homepage

2024-08-27 02:33 UTC, avenmia commented on src/components/survey/demographicssurvey.tsx
> +            </button>
Let's say "Re-enter Address"

2024-08-27 02:33 UTC, avenmia commented on src/pages/polis.tsx
> +            </button>
Let's say Retake Demographic Survey

2024-08-27 04:17 UTC, dinoboy197 commented on src/components/AddressSearch.tsx
> +              </button>
done

2024-08-27 04:17 UTC, dinoboy197 commented on src/components/survey/demographicssurvey.tsx
> +            </button>
done

2024-08-27 04:17 UTC, dinoboy197 commented on src/pages/polis.tsx
> +            </button>
done

2024-08-27 17:29 UTC, avenmia commented on src/pages/polissurvey.tsx
>          </Link>
Since we're updating the names, this might be better as "Select New Polis Survey"

2024-08-28 03:50 UTC, dinoboy197 commented on src/components/survey/demographicssurvey.tsx
> +            </button>
Done

2024-08-28 03:50 UTC, dinoboy197 commented on src/pages/polissurvey.tsx
>          </Link>
Done

2024-08-28 17:12 UTC, avenmia approved these changes
Lgtm! Thanks!

2024-08-29 00:53 UTC, merged